# Generated by Django 4.2.23 on 2025-08-25 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("pnumber", models.CharField(max_length=15)),
                ("birthDate", models.DateField(default=datetime.date(2000, 1, 1))),
                ("age", models.IntegerField(default=0)),
                ("weight", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=10)),
                ("symptoms", models.TextField(blank=True)),
                ("tests", models.TextField(blank=True)),
                ("addedSymptoms", models.JSONField(blank=True, default=list)),
                ("temperature", models.CharField(blank=True, max_length=10)),
                ("bp", models.CharField(blank=True, max_length=20)),
                ("oxy", models.CharField(blank=True, max_length=10)),
                ("medicine", models.TextField(blank=True)),
                ("medications", models.JSONField(blank=True, default=list)),
                ("instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
